openapi: 3.0.3
info:
  title: Disk Usage CLI Contracts (Preview)
  version: 0.1.0
  description: |
    Preview contract to keep CLI JSON outputs consistent and future API-ready.
    Not a running HTTP service in MVP; used for schema tracking and tests.
servers: []
paths:
  /summary:
    get:
      summary: Summarize direct children of a path
      parameters:
        - in: query
          name: path
          required: true
          schema: { type: string }
        - in: query
          name: basis
          schema: { type: string, enum: [physical, logical], default: physical }
        - in: query
          name: top
          schema: { type: integer, default: 10, minimum: 1 }
        - in: query
          name: sort
          schema: { type: string, enum: [size, files, dirs], default: size }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SummaryResponse'
components:
  schemas:
    SummaryResponse:
      type: object
      required: [root, basis, started_at, finished_at, entries]
      properties:
        root: { type: string }
        basis: { type: string, enum: [physical, logical] }
        started_at: { type: string, format: date-time }
        finished_at: { type: string, format: date-time }
        errors:
          type: array
          items: { $ref: '#/components/schemas/ErrorItem' }
        entries:
          type: array
          items: { $ref: '#/components/schemas/SummaryItem' }
    SummaryItem:
      type: object
      required: [path, size_bytes, file_count, dir_count, depth]
      properties:
        path: { type: string }
        size_bytes: { type: integer, format: int64, minimum: 0 }
        file_count: { type: integer, minimum: 0 }
        dir_count: { type: integer, minimum: 0 }
        depth: { type: integer, minimum: 0 }
    ErrorItem:
      type: object
      required: [path, code]
      properties:
        path: { type: string }
        code: { type: string }
        message: { type: string }
