[build]
# Build configuration

[target.'cfg(all())']
# Clippy linting levels
rustflags = [
    "-W", "clippy::all",
    "-W", "clippy::pedantic",
    "-A", "clippy::missing_errors_doc",
    "-A", "clippy::missing_panics_doc",
]
