name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Get version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## What's Changed
            
            See [RELEASE_NOTES.md](https://github.com/${{ github.repository }}/blob/${{ github.ref }}/RELEASE_NOTES.md) for details.
            
            ## Platform Support
            
            ### ✅ Fully Supported (Tested)
            - **Linux x86_64** (glibc and musl)
            - **Windows x86_64** (MSVC)
            
            ### ⚠️ Best Effort (Untested, should work)
            - **Linux ARM64** (aarch64)
            - **macOS** (Intel and Apple Silicon)
            
            ## Downloads
            
            Choose the appropriate binary for your platform:
            
            - `dua-v*-linux-x86_64`: Linux (glibc, requires libc)
            - `dua-v*-linux-x86_64-musl`: Linux (static, no dependencies) **← Recommended for Linux**
            - `dua-v*-linux-aarch64`: Linux ARM64 (Raspberry Pi, ARM servers)
            - `dua-v*-windows-x86_64.exe`: Windows 64-bit
            - `dua-v*-macos-x86_64`: macOS Intel
            - `dua-v*-macos-aarch64`: macOS Apple Silicon (M1/M2/M3)
          draft: false
          prerelease: false

  build:
    name: Build - ${{ matrix.name }}
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux - x86_64 (glibc)
          - name: Linux x86_64 (glibc)
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use-cross: false
            artifact_name: dua
            asset_name: dua-v${{ needs.create-release.outputs.version }}-linux-x86_64
          
          # Linux - x86_64 (musl, static)
          - name: Linux x86_64 (musl)
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            use-cross: false
            artifact_name: dua
            asset_name: dua-v${{ needs.create-release.outputs.version }}-linux-x86_64-musl
          
          # Linux - ARM64
          - name: Linux ARM64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            use-cross: true
            artifact_name: dua
            asset_name: dua-v${{ needs.create-release.outputs.version }}-linux-aarch64
          
          # Windows - x86_64
          - name: Windows x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            use-cross: false
            artifact_name: dua.exe
            asset_name: dua-v${{ needs.create-release.outputs.version }}-windows-x86_64.exe
          
          # macOS - x86_64 (Intel)
          - name: macOS x86_64
            os: macos-13
            target: x86_64-apple-darwin
            use-cross: false
            artifact_name: dua
            asset_name: dua-v${{ needs.create-release.outputs.version }}-macos-x86_64
          
          # macOS - ARM64 (Apple Silicon)
          - name: macOS ARM64
            os: macos-latest
            target: aarch64-apple-darwin
            use-cross: false
            artifact_name: dua
            asset_name: dua-v${{ needs.create-release.outputs.version }}-macos-aarch64

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross
        if: matrix.use-cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Setup musl tools (Linux musl only)
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Build release binary
        run: |
          BUILD_TOOL="${{ matrix.use-cross && 'cross' || 'cargo' }}"
          $BUILD_TOOL build --release --target ${{ matrix.target }}
        shell: bash

      - name: Run tests
        run: |
          BUILD_TOOL="${{ matrix.use-cross && 'cross' || 'cargo' }}"
          $BUILD_TOOL test --release --target ${{ matrix.target }}
        shell: bash

      - name: Prepare artifact
        run: |
          BINARY_PATH="target/${{ matrix.target }}/release/${{ matrix.artifact_name }}"
          cp "$BINARY_PATH" "${{ matrix.asset_name }}"
          
          # Create tarball for Unix-like systems
          if [ "${{ runner.os }}" != "Windows" ]; then
            tar czf "${{ matrix.asset_name }}.tar.gz" "${{ matrix.asset_name }}"
            echo "ASSET_PATH=${{ matrix.asset_name }}.tar.gz" >> $GITHUB_ENV
          else
            echo "ASSET_PATH=${{ matrix.asset_name }}" >> $GITHUB_ENV
          fi
          
          # Get binary size
          SIZE=$(du -h "${{ matrix.asset_name }}" | cut -f1)
          echo "Binary size: $SIZE"
        shell: bash

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ env.ASSET_PATH }}
          asset_name: ${{ env.ASSET_PATH }}
          asset_content_type: application/octet-stream

  checksums:
    name: Generate Checksums
    needs: [create-release, build]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Generate SHA256SUMS
        run: |
          sha256sum dua-* > SHA256SUMS.txt
          cat SHA256SUMS.txt

      - name: Upload checksums
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: SHA256SUMS.txt
          asset_name: SHA256SUMS.txt
          asset_content_type: text/plain
